language: node_js
node_js:
  - "14"
  - "13"
  - "12"
  - "node"
install: "npm install"
script: "npm run test"
after_success: "npm install -g coveralls && npm run coverage && cat ./coverage/lcov.info | coveralls"
