language: node_js
node_js:
  - "11"
  - "10"
  - "8"
  - "node"
install: "npm install && npm run build"
after_success: "npm install -g coveralls && npm run coverage && cat ./coverage/lcov.info | coveralls"
